=== aindlq/x3ml/src/test/resources/coin_a/original/MappingLanguage-v2.3.xsd
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>
This XML Schema is based on Mapping Language defined in "Mapping Language for Information Integration" Technical Report 385, ICS-FORTH, December 2006
</xs:documentation>
		<xs:documentation>
Institute of Computer Science, FORTH-ICS, Heraklio, Crete, Greece: Maria Koutraki(kutraki@ics.forth.gr) , Martin Doerr(martin@ics.forth.gr)
</xs:documentation>
		<xs:documentation>
The XML Schema was updated according to Gerald de Jong, DELVING document
<a href="http://www.cidoc-crm.org/mapping_technology/MappingDatatoCIDOC-CRM.pdf">Mapping Data to CIDOC-CRM</a>
, June 2013
</xs:documentation>
		<xs:documentation>Last Update: 12-11-2013</xs:documentation>
		<xs:documentation>
			<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">
				<img alt="Άδεια Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/88x31.png"/>
			</a>
			<br/>
Το
<span xmlns:dc="http://purl.org/dc/elements/1.1/" href="http://purl.org/dc/dcmitype/Text" property="dc:title" rel="dc:type">Mapping Language for Information Integration</span>
από τον
<a xmlns:cc="http://creativecommons.org/ns#" href="http://www.cidoc-crm.org/xsd/MappingLanguage_V1.0.xsd " property="cc:attributionName" rel="cc:attributionURL">
Institute of Computer Science, FORTH-ICS, http://www.ics.forth.gr
</a>
This work is licensed under a
<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">
Creative Commons Attribution-ShareAlike 3.0 Greece License
</a>
.
</xs:documentation>
	</xs:annotation>
	<xs:element name="mappings" type="mappingsComplexType">
		<xs:annotation>
			<xs:documentation>
Holds one or more mapping definitions from mapping-scheme-1 to mapping-schema-2 e.g. Lido to CIDOC-CRM
</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="mappingsComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="title" type="xs:string">
				<xs:annotation>
					<xs:documentation/>
					<xs:documentation/>
				</xs:annotation>
			</xs:element>
			<xs:element name="general_description" type="xs:string">
				<xs:annotation>
					<xs:documentation/>
				</xs:annotation>
			</xs:element>
			<xs:element name="source_info" type="source_infoComplexType">
				<xs:annotation>
					<xs:documentation/>
				</xs:annotation>
			</xs:element>
			<xs:element name="target_info" type="target_infoComplexType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation/>
				</xs:annotation>
			</xs:element>
			<xs:element name="mapping_info" type="mapping_infoComplexType">
				<xs:annotation>
					<xs:documentation/>
				</xs:annotation>
			</xs:element>
			<xs:element name="example_data_info" type="example_data_infoComplexType">
				<xs:annotation>
					<xs:documentation/>
				</xs:annotation>
			</xs:element>
			<xs:element ref="mapping" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation/>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute ref="version" use="required">
			<xs:annotation>
				<xs:documentation/>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="source_infoComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="source_schema">
				<xs:annotation>
					<xs:documentation/>
				</xs:annotation>
			</xs:element>
			<xs:element name="source_collection" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="source_schema">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="version" type="xs:string" use="required"/>
					<xs:attribute name="schema_file" type="xs:string"/>
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="target_infoComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="target_schema">
				<xs:annotation>
					<xs:documentation/>
				</xs:annotation>
			</xs:element>
			<xs:element name="target_collection" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="target_schema">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="version" type="xs:string" use="required"/>
					<xs:attribute name="schema_file" type="xs:string"/>
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="mapping_infoComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="mapping_created_by_org" type="xs:string"/>
			<xs:element name="mapping_created_by_person" type="xs:string"/>
			<xs:element name="in_collaboration_with" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="example_data_infoComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="example_data_from" type="xs:string"/>
			<xs:element name="example_data_contact_person" type="xs:string"/>
			<xs:element ref="example_data_source_record">
				<xs:annotation>
					<xs:documentation/>
				</xs:annotation>
			</xs:element>
			<xs:element ref="example_data_target_record"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="example_data_source_record">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="xml_link" type="xs:string"/>
					<xs:attribute name="html_link" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="example_data_target_record">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="rdf_link" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="mapping" type="mappingComplexType">
		<xs:annotation>
			<xs:documentation>one mapping definition</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="mappingComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="domain"/>
			<xs:element ref="link" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:attribute name="version" type="xs:decimal">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:attribute>
	<xs:element name="domain">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="domainComplexType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="domainComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="source"/>
			<xs:choice minOccurs="0">
				<xs:element ref="exists"/>
				<xs:element ref="or"/>
				<xs:element ref="and"/>
				<xs:element ref="not"/>
			</xs:choice>
			<xs:element ref="entity" maxOccurs="unbounded"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="internal_node" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="constant_node" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:element ref="comments" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="link" type="linkComplexType">
		<xs:annotation>
			<xs:documentation>Holds path and range</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="linkComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="path"/>
			<xs:element ref="range"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="source">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string"/>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="entity">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="entityComplexType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="entityComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence minOccurs="0">
			<xs:element ref="uri_function"/>
		</xs:sequence>
		<xs:attributeGroup ref="tag_entityNameType">
			<xs:annotation>
				<xs:documentation/>
			</xs:annotation>
		</xs:attributeGroup>
		<xs:attribute ref="binding">
			<xs:annotation>
				<xs:documentation/>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="variable" type="xs:string"/>
	</xs:complexType>
	<xs:attributeGroup name="tag_entityNameType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:attribute name="tag" type="xs:string">
			<xs:annotation>
				<xs:documentation/>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:attribute name="binding" type="xs:string">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="value" type="xs:string">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:attribute>
	<xs:element name="path" type="pathComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="pathComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="source"/>
			<xs:choice minOccurs="0">
				<xs:element ref="exists"/>
				<xs:element ref="or"/>
				<xs:element ref="and"/>
				<xs:element ref="not"/>
			</xs:choice>
			<xs:element ref="property"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="internal_node" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="constant_node" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:element ref="comments" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="range" type="rangeComplextype">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="rangeComplextype">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="source"/>
			<xs:choice minOccurs="0">
				<xs:element ref="exists"/>
				<xs:element ref="or"/>
				<xs:element ref="and"/>
				<xs:element ref="not"/>
			</xs:choice>
			<xs:element ref="entity" maxOccurs="unbounded"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="internal_node" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="constant_node" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:element ref="comments" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="uri_function" type="uri_functionComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="uri_functionComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="arg" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="name" use="required">
			<xs:annotation>
				<xs:documentation/>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:attribute name="name" type="xs:string">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:attribute>
	<xs:element name="property" type="propertyComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="propertyComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:attributeGroup ref="tag_propertyNameType">
			<xs:annotation>
				<xs:documentation/>
			</xs:annotation>
		</xs:attributeGroup>
	</xs:complexType>
	<xs:attributeGroup name="tag_propertyNameType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:attribute name="tag" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation/>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:element name="and" type="condition">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:element>
	<xs:element name="or" type="condition">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="condition">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="or"/>
				<xs:element ref="and"/>
				<xs:element ref="exists"/>
				<xs:element ref="not"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="not">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="exists"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="internal_node" type="internal_nodeComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="internal_nodeComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="entity" maxOccurs="unbounded"/>
			<xs:element ref="property"/>
			<xs:element ref="constant_node" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="constant_node" type="constant_nodeComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="constant_nodeComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="property"/>
			<xs:element ref="entity" maxOccurs="unbounded"/>
			<xs:element ref="internal_node" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="exists">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="value"/>
					<xs:attribute name="operator"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="arg" type="argComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="argComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="name">
					<xs:annotation>
						<xs:documentation/>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="comments" type="comments_ComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<!-- commments  -->
	</xs:element>
	<xs:complexType name="comments_ComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="rationale" type="xs:string"/>
			<xs:element name="alternatives" type="xs:string"/>
			<xs:element name="typical_mistakes" type="xs:string"/>
			<xs:element name="local_habits" type="xs:string"/>
			<xs:element name="link_to_cook_book" type="xs:string"/>
			<xs:element name="example" type="exampleComplexType"/>
			<xs:element ref="comments_last_update" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="exampleComplexType">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="example_source" type="xs:string" minOccurs="1"/>
			<xs:element name="example_target" type="xs:string" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="comments_last_update">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="date" type="xs:string" use="required"/>
					<xs:attribute name="person" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aindlq/x3ml/src/test/resources/coin_a/original/03.Coin-SimpleLink-wLabel.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="crm_mapping-v2.0.xsl"?>
<!--This document defines a mapping from OEAW Coins DB to CIDOC-CRM v5.0.1. 
based on the Mapping Language defined in "Mapping Language for Information Integration" Technical Report 385, ICS-FORTH, December 2006
and the suggested changes by Gerald de Jong --><!--Institute of Computer Science, FORTH-ICS, Heraklio, Crete, Greece: Maria Theodoridou(maria@ics.forth.gr) , Martin Doerr(martin@ics.forth.gr)--><mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="MappingLanguage-v2.3.xsd">
    <title>OEAW Coins DB (partial)</title>
    <general_description>Partial mapping of dFMRÖ (digitale FundMünzen der Römischen Zeit in Österreich), a database of ancient coin finds in Austria, to CIDOC-CRM.
The mapping was implemented within the ARIADNE project (http://www.ariadne-infrastructure.eu/)

</general_description>
    <source_info>
        <source_schema type="ER" version="">Relational DB - access</source_schema>
        <source_collection>dFMRÖ (digitale FundMünzen der Römischen Zeit in Österreich) (http://www.oeaw.ac.at/numismatik/projekte/dfmroe/dfmroe.html)</source_collection>
    </source_info>
    <target_info>
        <target_schema schema_file="../cidoc_crm_v5.1-draft-2013May.rdfs" type="rdfs" version="5.1">CIDOC-CRM</target_schema>
        <target_collection/>
    </target_info>
    <target_info>
        <target_schema schema_file="CRMtime_spans_v1.0___13-02-2014155935___11301.rdfs" type="rdfs" version="v1.0">CRMtime_spans</target_schema>
        <target_collection/>
    </target_info>
    <mapping_info>
        <mapping_created_by_org>OEAW (www.oeaw.ac.at/) and FORTH-ICS (www.ics.forth.gr)</mapping_created_by_org>
        <mapping_created_by_person>Elisabeth Pichler (Elisabeth.Pichler@oeaw.ac.at), Anja Masur (Anja.Masur@oeaw.ac.at), Martin Doerr (martin@ics.forth.gr), Maria Theodoridou (maria@ics.forth.gr)</mapping_created_by_person>
        <in_collaboration_with/>
    </mapping_info>
    <example_data_info>
        <example_data_from>record for coin 627</example_data_from>
        <example_data_contact_person>Maria Theodoridou (maria@ics.forth.gr)</example_data_contact_person>
        <example_data_source_record xml_link="Coin627in___13-02-2014154621___4036.xml">Coin627in.xml</example_data_source_record>
        <example_data_target_record rdf_link="Coin627out___24-02-2014170424___8439.rdf">Coin627out.rdf</example_data_target_record>
    </example_data_info>
    <mapping>
        <domain>
            <source>COIN</source>
            <entity tag="E22_Man-Made_Object">
                <uri_function name="UUID"/>
            </entity>
            <comments>
                <rationale>if a class "Exx Coin" is created as subclass of E22 Man-Made Object then we would map COIN to Exx Coin</rationale>
                <alternatives/>
                <typical_mistakes/>
                <local_habits/>
                <link_to_cook_book/>
                <example>
                    <example_source/>
                    <example_target/>
                </example>
                <comments_last_update date="" person=""/>
            </comments>
        </domain>
        <link>
            <path>
                <source>COIN/ID</source>
                <property tag="P1_is_identified_by"/>
                <comments>
                    <rationale>We map local identifiers in relational database tables explicitly only if these identifiers are visible in the user interface and used in other documents as well. Alternatively, we use the local database identifiers only for generating URIs for the record instance, here the coin instance, and do NOT map the COIN.ID at all.</rationale>
                    <alternatives/>
                    <typical_mistakes/>
                    <local_habits/>
                    <link_to_cook_book/>
                    <example>
                        <example_source/>
                        <example_target/>
                    </example>
                    <comments_last_update date="" person=""/>
                </comments>
            </path>
            <range>
                <source>COIN/ID</source>
					<entity tag="E41_Appellation">
						<uri_function name="UUIDwLabel">
							<arg name="label">COIN/ID</arg>
						</uri_function>
                    </entity>
            </range>
        </link>
        
    </mapping>
    
</mappings>
